# Generated by Django 3.2.13 on 2022-07-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_subproduct_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=255)),
                ('subCategories', models.CharField(max_length=255)),
                ('subProducts', models.CharField(max_length=255)),
            ],
        ),
    ]
